### ISSUE TITLE
Feature: Buffer option to say whether any lsp client should attach?

### ISSUE THREAD

**Issue by joshpetit** [neovim/nvim-lspconfig#1620]
### Requested feature

It would be nice if we could set some buffer option that will prevent lsps from attaching to it. This is something I asked about [on the octo.nvim](https://github.com/pwntester/octo.nvim/discussions/225) repo, but think it'd be nice if we could set an option that prevents any lsp from attaching to a buffer.

I'm not sure if an option would be the best way, but some method similar to that.

**Comment by mjlbach** [comment]
I already fixed the referenced issue in https://github.com/neovim/nvim-lspconfig/commit/abb3706974ca0b5086110d8f1b0e90daebff758f

**Comment by joshpetit** [comment]
Oh cool this was a recent fix! I'll take a look soon and let you know how if it's working, I remember it not the other day but I might not have been on the latest version.

**Comment by mjlbach** [comment]
No worries :) 

I'm working on the successor to lspconfig, which amongst other things will let you define more complex project markers that will make distinguishing between say, a typescript and deno project easier (which IMO is the main motivation for the feature you are requesting besides the issue I have already fixed)

**Comment by joshpetit** [comment]
Alright so taking a look at it, the dart lsp is still attaching to the octo buffer. I tested this with tsserver and it didn't attach. So this makes me think it's probably just dartls specific, I use [flutter-tools](https://github.com/akinsho/flutter-tools.nvim) instead of the lsp config directly so it may do something that's causing the bug to still happen, not positive 🤷.

Either way considering nvim lspconfig `#2` is on the way I'll be fine just waiting haha. All it really does is throw incessant exceptions when trying to attach:
```
LSP[dartls] URI was not a valid file:// URI
```

Either way I'll leave it to you to close this issue if you want since it doesn't bother me much and probably will be fixed with the successor! I'm excited.

**Comment by mjlbach** [comment]
Can you verify you don't have the bug when not using flutter-tools?

**Comment by joshpetit** [comment]
After going to another project I see that tailwind-css' language server also tries attaching to the octo buffer. So I'm guessing this has to do with the lsp directly. It might be with how octo create's the buffers that causes the problem.

**Comment by mjlbach** [comment]
What are the exact reproduction steps for this? I've never used octo.

**Comment by joshpetit** [comment]
Yea so this is what I would do:
1. First install Octo
2. Create a PR on a repository (Octo pr create
3. Start a review of the PR (Octo review start)
4. The lsps try to attach to the buffers that are created for the diffs.

The error is this:
```
LSP[dartls] URI was not a valid file:// URI
```
And the path (`!echo %`) is (for one of the diffs):
```
octo://REPO/PATH/review/PRR_kwDOFoTYws4yNZ98/file/RIGHT/lib/features/event/update_card.dart
```

Is there something else I can give you that might help? Thanks!

**Comment by mjlbach** [comment]
Interesting, I don't have the issue with lua-language-server at least. This line https://github.com/neovim/nvim-lspconfig/blob/abb3706974ca0b5086110d8f1b0e90daebff758f/lua/lspconfig/util.lua#L23 should not match on "octo" prefixed URIs (which is the case on my computer at least.

**Comment by mjlbach** [comment]
Hey @joshpetit any updates? Can you send me the minimal repro for tailwind or dartls using the minimal init.lua and an example file? I wasn't able to reproduce with the latest lspconfig with your example.

**Comment by joshpetit** [comment]
@mjlbach Sorry! Semester started recently so haven't really had much time :sweat:, I assume this isn't a problem for most people so I'll just bear with it and may look into this more later! Thansk for all the help

**Comment by TimothyKrell** [comment]
> 

@mjlbach Did you end up creating a solution for this? I have an issue that would be fixed by it.
