### ISSUE TITLE
jsonls formatting doesn't work with default config

### ISSUE THREAD

**Issue by nkhlmn** [neovim/nvim-lspconfig#372]
- `nvim --version`:
```
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200926-34765-q16uln/build/config -I/tmp/neovim-20200926-34765-q16uln/src -I/usr/local/include -I/tmp/neovim-20200926-34765-q16uln/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200926-34765-q16uln/build/src/nvim/auto -I/tmp/neovim-20200926-34765-q16uln/build/include
Compiled by <redacted>

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-4a996bc/share/nvim"

Run :checkhealth for more info
```

- nvim-lsp version(commit hash):
Whatever comes with 0.5 nightly? How do I find this?

- `:checkhealth` result
Perl/ruby provider not installed but all good otherwise

- What language server(If the problem is related to a specific language server):
jsonls

- Operating system/version: 
macOS 10.15.6

- Terminal name/version:
kitty 0.18.3

- `$TERM`:
xterm-kitty

### How to reproduce the problem from neovim startup
- Use the following plugins (installed with vimplug): nvim-lspconfig, completion-nvim, diagnostic-nvim
- Install jsonls using `LspInstall`
- Use following config:

```
local on_attach = function(client)
  print("LSP started.");
  require'completion'.on_attach(client)
  require'diagnostic'.on_attach(client)
end

require'nvim_lsp'.jsonls.setup{ on_attach=on_attach }

nnoremap <silent> <leader>f <cmd>lua vim.lsp.buf.formatting()<CR>
```
- Tried formatting a JSON file using `<leader> f`

I'm also using this setup with tsserver and rust_analyzer with success.

### Actual behaviour
Nothing happens.

### Expected behaviour
Document is formatted.

**Comment by jerrywang1981** [comment]
try this
```
nnoremap <silent> <leader>f <cmd>lua vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})<CR>
```

**Comment by nkhlmn** [comment]
That does not work either

**Comment by jerrywang1981** [comment]
what does your json file look like? last line to be `}` ? 
```
{ "o": 1, "p": "2"
}
``` 
for me this formats to 
```
{
  "o": 1,
  "p": "2"
}
```

**Comment by s-zeng** [comment]
> try this
> 
> ```
> nnoremap <silent> <leader>f <cmd>lua vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})<CR>
> ```

This command works for me whereas the standard vim.lsp.buf.formatting does not

**Comment by jerrywang1981** [comment]
> That does not work either

add this to your setup
```
  init_options = {
    provideFormatter = true
  }
```
so your could would be:
```
require'nvim_lsp'.jsonls.setup{ 
     on_attach=on_attach,
     init_options = {
      provideFormatter = true
    }
}
```

**Comment by nkhlmn** [comment]
No luck with that either

**Comment by jerrywang1981** [comment]
can you:
1. make sure there is a blank line at the end of the file
or 
2. try this (a little difference from previous one)
`nnoremap <silent> <leader>f <cmd>lua vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$")+1,0})<CR>`
or 
3. did you make sure the client was attached?
`:lua print(vim.inspect(vim.lsp.get_active_clients()))`

**Comment by mjlbach** [comment]
This depends on dynamicRegistration, which neovim does not support. The documentation makes it appear as if the following will work. 

``` lua
  init_options = {
    provideFormatter = true;
  };
  settings = { 
    json = {
      format = "enable";
    };
  };
```

See: https://github.com/vscode-langservers/vscode-json-languageserver/blob/master/README.md#settings

https://github.com/vscode-langservers/vscode-json-languageserver/blob/dba91ca3e8f571c2ffec72ec3da110adc520bce2/src/jsonServer.ts#L128

https://github.com/vscode-langservers/vscode-json-languageserver/blob/dba91ca3e8f571c2ffec72ec3da110adc520bce2/src/jsonServer.ts#L224-L234

https://github.com/vscode-langservers/vscode-json-languageserver/blob/dba91ca3e8f571c2ffec72ec3da110adc520bce2/src/jsonServer.ts#L140

**Comment by mjlbach** [comment]
You can follow the issue here: https://github.com/neovim/neovim/issues/13634

**Comment by mjlbach** [comment]
Can you all try this PR? https://github.com/neovim/neovim/pull/13642
`:lua vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})` works for me, note jsonls only provides rangeFormatting

**Comment by mjlbach** [comment]
Fixed in #518, would appreciate testers/commentary

**Comment by benjaminbauer** [comment]
@mjlbach thank you for the fix! `:lua vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})` works great. Just when I put the proposed block in the setup in my init.vim (as per the updated REAMDE), I still get: `method textDocument/formatting is not supported by any of the servers...` when I call `:lua vim.lsp.buf.formatting()`

Is my assumption wrong, that `vim.lsp.buf.formatting()` should work with after adding the block to jsonls setup?

**Comment by mjlbach** [comment]
`:lua vim.lsp.buf.formatting()` is not the same as `:lua vim.lsp.buf.range_formatting()`, they are implemented/supported separately in the lsp spec.

You need to map a command, I have this in my config.

```lua
nvim_lsp.jsonls.setup {
  commands = {
    Format = {
      function()
        vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})
      end
    }
  }
}
```

call with `:Format`

**Comment by benjaminbauer** [comment]
Ok, I was hoping that it would make `vim.lsp.buf.formatting()` work so I can keep using my keybinding for formatting. But in this case I probably have to define an exception depending on the document type `json`

**Comment by cloggier** [comment]
@mjlbach Understanding that this is way out of the scope of support here I would greatly appreciate some help (might benefit others too).
 I have mostly copy and paste Lukas' formatting solution from https://github.com/lukas-reineke/dotfiles/blob/master/vim/lua/lsp.lua — do you think it is possible to change it in a way that it would execute `range_formatting` for `jsonls` alone and `formatting()` for others?

**Comment by mjlbach** [comment]
@benjaminbauer You can use on_attach to make the same key refer to multiple bindings depending on which lsp is attached. So you can have <space>f refer to range_formatting in json, and <space>f refer to format everywhere else.

```vim
lua << EOF
local nvim_lsp = require('lspconfig')
local on_attach = function(_, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }
  buf_set_keymap('n', '<space>f', '<Cmd>lua vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})<CR>', opts)
end

nvim_lsp['jsonls'].setup { on_attach = on_attach }
EOF
```

**Comment by cloggier** [comment]
@mjlbach Yes, that I am aware of, thanks. My question was in regards to automatic formatting on save which Lukas has come up with. Which works like magic BTW! Great thanks for that @lukas-reineke.

**Comment by mjlbach** [comment]
Sure, you just again use on_attach, but set it to call the autocommand for the bufnr.

**Comment by cloggier** [comment]
Ah, that's it! Thanks. Also, I can see that `on_attach()` receives `client` table, so probably instead of having multiple functions one could use conditionals in one.

**Comment by mjlbach** [comment]
I was just trying to make it super explicit, one of the advantages of this being all lua is there a a bajillion cool ways to do things ⭐

**Comment by cloggier** [comment]
Just noticed `jsonls` does not return support for `client.resolved_capabilities.document_formatting` capability. Should it given there is formatting? I know I can set it myself though.

**Comment by mjlbach** [comment]
>:lua vim.lsp.buf.formatting() is not the same as :lua vim.lsp.buf.range_formatting(), they are implemented/supported separately in the lsp spec. Jsonls supports the latter, not the former, so :lua vim.lsp.buf.formatting() will never work.

**Comment by cloggier** [comment]
@mjlbach Super star! Thanks!

**Comment by mjlbach** [comment]
Just to clarify for posterity, `resolved_capabilities` refers to the *server* not the neovim client

**Comment by cpkio** [comment]
The function `vim.lsp.buf.range_formatting()` that provides formatting for `jsonls` is going to be deprecated in Nvim 0.9, being replaced with `vim.lsp.formatexpr()` or `vim.lsp.buf.format()`. How can I do formatting via `jsonls` with any of those functions?

`jsonls` only provides rangeFormatting, we know that.

The Nvim 0.8.2 help says

```
format({options})                                       *vim.lsp.buf.format()*
    Formats a buffer using the attached (and optionally filtered) language
    server clients.

    Parameters:  
      • {options}  table|nil Optional table which holds the following optional
                   fields:
                   • range (table|nil) Range to format. Table must contain
                     `start` and `end` keys with {row, col} tuples using (1,0)
                     indexing. Defaults to current selection in visual mode
                     Defaults to `nil` in other modes, formatting the full
                     buffer
```

I've tried this:

```
vim.api.nvim_set_keymap('n', '<leader>f', '', { silent = true, callback = function()
  vim.lsp.buf.format({
    async = true,
    range = {
      ["start"] = { 0,0 }, -- tried { 1, 0 } too
      ["end"] = { vim.fn.line("$"),0 }
    }
  })
end })
```

I get `Format request failed, no matching language servers.` message. Couldn't make it work in visual mode too. Maybe nvim implementation of ranges in `format()` is broken?
