### ISSUE TITLE
Svelte is not reflect typescript file

### ISSUE THREAD

**Issue by windwp** [neovim/nvim-lspconfig#725]
My svelte server is working but it is not reflect the change of typescript file 

### How to reproduce the problem from neovim startup

- Open neovim, open svelte file.
-  import another typescript file to that svelte file
-  go to typescript file and change code and save that file
-  svelte don't understand the update code.

if i quit neovim and reopen that file svelte will know that change .

### Actual behaviour
it don't reflect the change in typesciprt
### Expected behaviour
it need to know the update code.

i check and this issue happen with coc-svelte but it work on vscode.

**Comment by mjlbach** [comment]
I don't think this is an issue with nvim-lspconfig, but an issue with neovim core's implementation. This repo only handles initialization the language server, none of the functionality of the language server client. Unless you can find a specific setting we are not sending to the language server, please file an issue with the neovim core repo.

**Comment by mjlbach** [comment]
I stepped away from the project and don't actively use neovim anymore.

This could/should probably be changed to a `didChangeWatchedFiles` and filtered server side https://github.com/sveltejs/language-tools/blob/09a2dbdca0ecd25ca2750beaabd305d718b359d1/packages/language-server/src/server.ts#L452-L459, that way it's spec-compliant.

A file watcher was added to neovim circa 0.9 based on my cursory glance at the commits. Worst case is you could wrap that to send an additional notification. I have no code suggestions for you and will not work on it.

**Comment by ryoppippi** [comment]
|'m in the same problem! https://github.com/sveltejs/language-tools/issues/1415#issuecomment-1539681042

**Comment by ryoppippi** [comment]
https://github.com/sveltejs/language-tools/issues/2008#issuecomment-1539788464
Here is my solution

**Comment by RichGuk** [comment]
> 

@ryoppippi Nice! Thanks for the workaround. Can it be simplified as:

```lua
lspconfig.svelte.setup {
  on_attach = function(client)
    vim.api.nvim_create_autocmd("BufWritePost", {
      pattern = { "*.js", "*.ts" },
      callback = function(ctx)
        client.notify("$/onDidChangeTsOrJsFile", { uri = ctx.file })
      end,
    })
  end
}
```

**Comment by glepnir** [comment]
pattern would be better use your project root `root/*.js `.

**Comment by jasonlyu123** [comment]
Hi. I am a maintainer of @sveltejs/language-tools. `onDidChangeTsOrJsFile` is a custom endpoint for syncing in editor file changes. Is the problem with the file watcher not triggering or updates only working when the file is saved?  We have `didChangeWatchedFiles`, but the file watcher config is set in the client.

**Comment by RichGuk** [comment]
@jasonlyu123 Not too sure if its an issue with the langauge-server? From a bit of digging around it looks like the VSCode extension handles this client side? So if I add a property in the `.ts` file, the `.svelte` component won't see the new property without a restart of the editor/svelte language server.

The above code does actually seem to solve the issue. I think it replicates what's happening here: https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/src/extension.ts#L312

**Comment by glepnir** [comment]
maybe need  manually set the capability `workspace.didChangeWatchedFiles.dynamicRegistration = true`

**Comment by jasonlyu123** [comment]
@RichGuk Yes, I see that in your previous comment. Do you expect the change to reflect if the file is saved to the file system or if you expect it to work without file save? These are different issues.

**Comment by RichGuk** [comment]
@jasonlyu123 I would expect it to work on save, personally.

**Comment by glepnir** [comment]
For 0.9 user try this

```lua
local updated_capabilities = vim.lsp.protocol.make_client_capabilities()
updated_capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true
```

**Comment by ryoppippi** [comment]
@glepnir What is that didchangedwatchedfiles option? Is it on `vim.lsp`?

**Comment by jasonlyu123** [comment]
Unlike Volar, we didn't use dynamicRegistration for file watchers. The file watcher glob is set in clients. We also have a fallback if the client doesn't support `didChangeWatchedFiles`. That means if the client supports `didChangeWatchedFiles` but doesn't configure the watcher glob in the client. Files won't be watched. Since multiple people suddenly have the problem, I'll assume this is because 0.9 added the support, so our fallback isn't used.

And if the watcher works, the `onDidChangeTsOrJsFile` endpoint is only needed if you want changes to reflect without needing to save the file first.

**Comment by RichGuk** [comment]
@ryoppippi neovim lsp

> Added preliminary support for the workspace/didChangeWatchedFiles capability to the LSP client to notify servers of file changes on disk. The feature is disabled by default and can be enabled by setting the workspace.didChangeWatchedFiles.dynamicRegistration=true capability.

**Comment by ryoppippi** [comment]
@RichGuk @glepnir 
Thanks!
I tried this(https://github.com/neovim/nvim-lspconfig/issues/725#issuecomment-1539868397) without my autocmd configure, but it does not work for me

**Comment by glepnir** [comment]
I forget its true by default

```lua
      didChangeWatchedFiles = {
        dynamicRegistration = true,
        relativePatternSupport = true,
      },
```

>  The file watcher glob is set in clients. We also have a fallback if the client doesn't support didChangeWatchedFiles. That means if the client supports didChangeWatchedFiles but doesn't configure the watcher glob in the client. Files won't be watched. 

maybe problem here. there not config the glob but we support didChangWatchedFiles.

**Comment by ryoppippi** [comment]
@glepnir 
hmm, still does not work
we still need this↓
```lua
            client.notify("$/onDidChangeTsOrJsFile", { uri = ctx.file })
```

**Comment by ryoppippi** [comment]
@jasonlyu123 Thank you so much!
Okay, for now when I create a new file, I restart my LSP and it works.

>I tried moving the watcher registration to the language server with dynamic registration. It fixed the issue, and the existing client with configs on the client side seems to be working fine. So I think we can fix this on our side.

Can I try the new one?

**Comment by josuetorr** [comment]
I found a somewhat "silly" solution. You can name your files `.svelte` and set the script tag's `context` attribute to `module` and simply export whatever you what as plain typescript.

**Comment by nucleus48** [comment]
neovim will allow lsp servers to dynamically register didChangeWatchedFiles even if dynamic registration is set to false, which is the default value, but svelte lsp need dynamic registration to be true before registering didChangeWatchedFiles.
`local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true
`
this should solve the problem.

**Comment by ryoppippi** [comment]
I already enabled `dynamicRegistration` before my hack but it didn't work

**Comment by ryoppippi** [comment]
I found that we do not need to set this hack anymore.
https://github.com/neovim/nvim-lspconfig/issues/725#issuecomment-1539822348
https://github.com/neovim/nvim-lspconfig/issues/725#issuecomment-1539789005

**Comment by pierregoutheraud** [comment]
@ryoppippi I still have the issue with `.svelte.ts` files.
Can you tell us what config you have ?

Here is mine right now:

```lua
local lspconfig = require("lspconfig")
local lsp_capabilities = require("cmp_nvim_lsp").default_capabilities()

local default_setup = function(server)
	lspconfig[server].setup({
		capabilities = lsp_capabilities,
	})
end

require("mason").setup({})
require("mason-lspconfig").setup({
	ensure_installed = {},
	handlers = {
		default_setup,
		svelte = function()
			lspconfig.svelte.setup({
				on_attach = function(client)
					vim.api.nvim_create_autocmd("BufWritePost", {
						pattern = { "*.js", "*.ts" },
						callback = function(ctx)
							print("svelte lsp BufWritePost")
							print(ctx.file)
							client.notify("$/onDidChangeTsOrJsFile", { uri = ctx.file })
						end,
					})
				end,
                               ...

```

**Comment by pierregoutheraud** [comment]
After many many tests. I found an hint of where the origin of the problem is.

For my tests I open a svelte component file and then a ts file. I export a variable from the ts file and see if I get the changes in the svelte file.

- If I open the test.ts file with the plugin oil.nvim then LSP will update. 
- If I open the test.ts file with the plugin telescope then LSP will NOT update.

https://github.com/neovim/nvim-lspconfig/assets/1341781/bc2dc384-b635-4714-a5c3-d1c7f48bfac0

Does anyone have an idea why?

**Comment by ryoppippi** [comment]
@pierregoutheraud This is what I suggested !

**Comment by ryoppippi** [comment]
@pierregoutheraud 
Hi! 
Let me know the difference btw `ctx.match` and `ctx.file`
Actually, `match` works fine!

**Comment by pierregoutheraud** [comment]
@ryoppippi `ctx.match` is always an absolute path. `ctx.file` will sometimes be a relative path and will then sometimes not work.

**Comment by ryoppippi** [comment]
@pierregoutheraud got it. 
I'll use this one! Thx
